[workspace]
members = [
    "abi/synapse-abi",
    "abi/synapse-abi-buildgen",
    "abi/synapse-abi-core",
    "abi/synapse-abi-suite",
    "abi/synapse-abi-ext",
    "crates/synapse-host-mini",
    "crates/test-scalar-plugin",
    "crates/synapse-host-abi",
    "crates/synapse-sdk",
    "crates/test-scalar-sdk",
]
resolver = "2"
